### ISSUE TITLE
Problem in sklearn version check

### ISSUE THREAD

**Issue by mpharrigan** [pandegroup/osprey#58]
```
Traceback (most recent call last):                                              
  File "/home/harrigan/opt/python/bin//osprey", line 9, in <module>             
    load_entry_point('osprey==0.4', 'console_scripts', 'osprey')()              
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/osprey-0.4-py3.4.egg/osprey/cli/main.py", line 35, in main
    args_func(args, p)                                                          
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/osprey-0.4-py3.4.egg/osprey/cli/main.py", line 40, in args_func
    args.func(args, p)                                                          
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/osprey-0.4-py3.4.egg/osprey/cli/parser_worker.py", line 7, in func
    from ..execute_worker import execute                                        
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/osprey-0.4-py3.4.egg/osprey/execute_worker.py", line 20, in <module>
    from .fit_estimator import fit_and_score_estimator                          
  File "/home/harrigan/opt/python/lib/python3.4/site-packages/osprey-0.4-py3.4.egg/osprey/fit_estimator.py", line 19, in <module>
    if LooseVersion(sklearn.__version__) < LooseVersion('0.15.0'):              
  File "/home/harrigan/opt/python/lib/python3.4/distutils/version.py", line 58, in __lt__
    c = self._cmp(other)                                                        
  File "/home/harrigan/opt/python/lib/python3.4/distutils/version.py", line 343, in _cmp
    if self.version < other.version:                                            
TypeError: unorderable types: str() < int()   
```

**Comment by anuja-kelkar** [comment]
Even after uisng conda version of sklearn, I am getting the following error:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-4620636caab1> in <module>()
     20 
     21 clf = ensemble.RandomForestClassifier(n_estimators = 500, n_jobs = -1)
---> 22 clf.fit(X_train, y)

/Users/anujamkelkar/anaconda/lib/python3.4/site-packages/sklearn/ensemble/forest.py in fit(self, X, y, sample_weight)
    216         self.n_outputs_ = y.shape[1]
    217 
--> 218         y, expanded_class_weight = self._validate_y_class_weight(y)
    219 
    220         if getattr(y, "dtype", None) != DOUBLE or not y.flags.contiguous:

/Users/anujamkelkar/anaconda/lib/python3.4/site-packages/sklearn/ensemble/forest.py in _validate_y_class_weight(self, y)
    405 
    406         for k in range(self.n_outputs_):
--> 407             classes_k, y[:, k] = np.unique(y[:, k], return_inverse=True)
    408             self.classes_.append(classes_k)
    409             self.n_classes_.append(classes_k.shape[0])

/Users/anujamkelkar/anaconda/lib/python3.4/site-packages/numpy/lib/arraysetops.py in unique(ar, return_index, return_inverse, return_counts)
    191 
    192     if optional_indices:
--> 193         perm = ar.argsort(kind='mergesort' if return_index else 'quicksort')
    194         aux = ar[perm]
    195     else:

TypeError: unorderable types: str() > int()
```

**Comment by rmcgibbo** [comment]
This looks like a sklearn error in the random forest code, not an osprey error. Or maybe your `y` data is not the proper type?

**Comment by anuja-kelkar** [comment]
Thanks for the help. y was in wrong format.
